/*
 * Aplikacja
 *
 * Społecznościowy system informowania o cenach paliw. 
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using WebApplication2.Models;
using WebApplication2.Data;

namespace WebApplication2.Controllers
{
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class CommentController : ControllerBase
    {
        private readonly WebApplication2Context _context;

        public CommentController(WebApplication2Context context)
        {
            _context = context;
        }
        /// <summary>
        /// Show Comment info
        /// </summary>
        /// <remarks>Pokazuje komentarz</remarks>
        /// <param name="commentID">ID komentarza do wyświetlenia</param>
        /// <param name="token">Token zalogowanego użytkownika</param>
        /// <response code="401">Not authenticated</response>
        /// <response code="0">successful operation</response>
        [HttpGet]
        [Route("/Comment/{Comment_ID}")]
        public virtual IActionResult CommentCommentIDGet([FromRoute][Required] int? commentID, [FromHeader][Required()] string token)
        {

            //TODO: Uncomment the next line to return response 401 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(401);

            //TODO: Uncomment the next line to return response 0 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(0);


            throw new NotImplementedException();
        }

        /// <summary>
        /// Edit comment
        /// </summary>
        /// <remarks>Zedytuj teskt komentarza.</remarks>
        /// <param name="commentID">ID komentarza do edycji</param>
        /// <param name="token">Token zalogowanego użytkownika</param>
        /// <param name="commentChange">Nowy tekst komentarza</param>
        /// <response code="401">Not authenticated</response>
        /// <response code="0">successful operation</response>
        [HttpPut]
        [Route("/comment/edit/{Comment_ID}")]
        public virtual IActionResult CommentEditCommentIDPut([FromRoute][Required] int? commentID, [FromHeader][Required()] string token, [FromBody] CommentChange commentChange)
        {
            //TODO: Uncomment the next line to return response 401 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(401);

            //TODO: Uncomment the next line to return response 0 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(0);


            throw new NotImplementedException();
        }

        /// <summary>
        /// Post new comment
        /// </summary>
        /// <remarks>Wyślij nowy komentarz.</remarks>
        /// <param name="token">Token zalogowanego użytkownika</param>
        /// <param name="comment">Komentarz</param>
        /// <response code="401">Not authenticated</response>
        /// <response code="0">successful operation</response>
        [HttpPost]
        [Route("/comment")]

        public virtual IActionResult CommentPost([FromHeader][Required()] string token, [FromBody] Comment comment)
        {
            if (ModelState.IsValid)
            {
                comment.Id = null;
                _context.Add(comment);
                _context.SaveChanges();
                return StatusCode(0);
            }
            else return StatusCode(401);
            //TODO: Uncomment the next line to return response 401 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(401);

            //TODO: Uncomment the next line to return response 0 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // 


            throw new NotImplementedException();
        }

        /// <summary>
        /// Delete comment
        /// </summary>
        /// <remarks>Usuwa komentarz</remarks>
        /// <param name="commentID">ID komentarza do usnięcia</param>
        /// <param name="token">Token zalogowanego użytkownika</param>
        /// <response code="401">Not authenticated</response>
        /// <response code="0">successful operation</response>
        [HttpDelete]
        [Route("/comment/remove/{commentID}")]

        public virtual IActionResult CommentRemoveCommentIDDelete([FromRoute][Required] int? commentID, [FromHeader][Required()] string token)
        {
            var com = _context.Comment.Find(commentID);
            if (com != null) {
                _context.Comment.Remove(com);
                _context.SaveChanges();
                return StatusCode(200);
            }
            //TODO: Uncomment the next line to return response 401 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(401);

            //TODO: Uncomment the next line to return response 0 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(0);


            throw new NotImplementedException();
        }
    }

}
