/*
 * Aplikacja
 *
 * Społecznościowy system informowania o cenach paliw. 
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using IO.Swagger.Attributes;
using IO.Swagger.Security;
using Microsoft.AspNetCore.Authorization;
using WebApplication2.Models;
using WebApplication2.Data;
using System.Linq;
using PSIM2.Security;
using Microsoft.EntityFrameworkCore;

namespace IO.Swagger.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class UserApiController : ControllerBase
    {
        private readonly WebApplication2Context _context;

        public UserApiController(WebApplication2Context context)
        {
            _context = context;
        }
        /// <summary>
        /// Create User
        /// </summary>
        /// <remarks>Tworzy użytkownika</remarks>
        /// <param name="uytkownik">Tworzy użytkownicy</param>
        /// <response code="0">successful operation</response>
        [HttpPost]
        [Route("/register")]
        [ValidateModelState]
        public virtual IActionResult CreateUser([FromBody] User uytkownik)
        {
            /*_context.User.Add(new User() { Login = "jp2", Email = "pope@21.37", Role = 1, Password = "123", Name = "Karol", Surname = "Wojtyła", Locaction = "Watykan city" });
            _context.SaveChanges();
            return StatusCode(200, "done");*/
            if (ModelState.IsValid)
            {
                uytkownik.Id = null;
                uytkownik.Role = _context.Role.Where(x => x.Id == uytkownik.Role.Id).FirstOrDefault();
                if (uytkownik.Password.Length < 8)
                    return StatusCode(400, "Password too short");
                uytkownik.Password = PasswordManager.HashPassword(uytkownik.Password, 1001, 70);
                _context.User.Add(uytkownik);
                _context.SaveChanges();
                return StatusCode(200, uytkownik);
            }
            //TODO: Uncomment the next line to return response 0 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            return StatusCode(400);
        }

        /// <summary>
        /// Delete User info
        /// </summary>
        /// <remarks>Usuwa info o użytkowniku.</remarks>
        /// <param name="userID">ID użytkownika do usunięcia</param>
        /// <param name="token">Token zalogowanego użytkownika</param>
        /// <response code="401">Not authenticated</response>
        /// <response code="0">successful operation</response>
        [HttpDelete]
        [Route("/User/remove/{userID}")]
        [ValidateModelState]
        public virtual IActionResult Delinfo([FromRoute][Required]int? userID, [FromHeader][Required()]string token)
        {
            long? requesterID;
            try
            {
                requesterID = (long?)TokenManager.VerifyToken(token)["userId"];
            }
            catch (Exception ex)
            {
                return StatusCode(401);
            }
            var user = _context.User.Where(x => x.Id == userID).FirstOrDefault();
            if (user != null) {
                _context.User.Remove(user);
                _context.SaveChanges();
                return StatusCode(200);
            }

            //TODO: Uncomment the next line to return response 401 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(401);

            //TODO: Uncomment the next line to return response 0 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(0);


            throw new NotImplementedException();
        }

        /// <summary>
        /// Edit user info
        /// </summary>
        /// <remarks>Zedytuj niektóre dane o użytkowniku.</remarks>
        /// <param name="userIDEdit">ID użytkownika do edycji</param>
        /// <param name="token">Token zalogowanego użytkownika proszącego o dane</param>
        /// <param name="userChange">Pola użytkownika z nowymi wartościami</param>
        /// <response code="401">Not authenticated</response>
        /// <response code="0">successful operation</response>
        [HttpPut]
        [Route("/User/edit/{userIDEdit}")]
        [ValidateModelState]
        public virtual IActionResult Editinfo([FromRoute][Required]int? userIDEdit, [FromHeader][Required()]string token, [FromBody]UserChange userChange)
        {
            long? requesterID;
            try
            {
                requesterID = (long?)TokenManager.VerifyToken(token)["userId"];
            }
            catch (Exception ex)
            {
                return StatusCode(401);
            }
            var user = _context.User.Where(x => x.Id == userIDEdit).FirstOrDefault();
            if (user != null) {
                user.Login = userChange.Login;
                user.Password = userChange.Passowrd;
                user.Locaction = userChange.Locaction;
                user.Role = userChange.Role;
                user.Surname = userChange.Surname;
                user.Name = userChange.Name;
                user.Email = userChange.Email;
                _context.User.Update(user);
                _context.SaveChanges();
                return StatusCode(0);

            }
            //TODO: Uncomment the next line to return response 401 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(401);

            //TODO: Uncomment the next line to return response 0 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(0);


            throw new NotImplementedException();
        }

        /// <summary>
        /// Show User info
        /// </summary>
        /// <remarks>Pokazuje info o użytkowniku.</remarks>
        /// <param name="userID">ID użytkownika do wyświetlenia</param>
        /// <param name="token">Token zalogowanego użytkownika proszącego o dane</param>
        /// <response code="401">Not authenticated</response>
        /// <response code="0">successful operation</response>
        [HttpGet]
        [Route("/User/{userID}")]
        [ValidateModelState]
        public virtual IActionResult Showinfo([FromRoute][Required]int? userID, [FromHeader][Required]string token)
        {
            _context.User.Include(b => b.Role).ToList();
            long? requesterID;
            try
            {
                requesterID = (long?)TokenManager.VerifyToken(token)["userId"];
            }
            catch (Exception ex)
            {
                return StatusCode(401);
            }
            var user = _context.User.Where(x => x.Id == userID).FirstOrDefault();
            if (requesterID == userID)
            {
                if (user != null)
                    return StatusCode(200, user);
                else
                    return StatusCode(404);
            }
            else
            {
                User requester = _context.User.Where(x => x.Id == requesterID).FirstOrDefault();
                if (requester != null && (bool)requester.Role.IsAdmin)
                {
                    if (user != null)
                        return StatusCode(200, user);
                    else
                        return StatusCode(404);
                }
                else
                {
                    return StatusCode(403);
                }
            }
        }
    }
}
