/*
 * Aplikacja
 *
 * Społecznościowy system informowania o cenach paliw. 
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System.ComponentModel.DataAnnotations;

namespace WebApplication2.Models
{
    public class Address
    {
        [Key]
        public int Id { get; set; }
        public string City { get; set;}
        public string Street { get; set; }
        public int StreetNo { get; set; }

    }
}